package com.bof.mobile.ui.accounts

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.KeyboardArrowDown
import androidx.compose.material.icons.filled.Visibility
import androidx.compose.material.icons.filled.VisibilityOff
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import com.bof.mobile.data.repository.AccountRepository
import com.bof.mobile.model.ApiResult
import com.bof.mobile.model.CreateAccountRequest
import com.bof.mobile.ui.components.ScreenHeader
import kotlinx.coroutines.launch

private val REQUESTABLE_ACCOUNT_TYPES = listOf("Simple Access", "Savings")

@Composable
fun CreateAccountScreen(
    accountRepository: AccountRepository,
    customerId: Int,
    canGoBack: Boolean,
    onBack: () -> Unit,
    onAccountCreated: (com.bof.mobile.model.AccountItem) -> Unit = {}
) {
    val scope = rememberCoroutineScope()

    var accountName by remember { mutableStateOf("") }
    var accountType by remember { mutableStateOf(REQUESTABLE_ACCOUNT_TYPES.first()) }
    var accountTypeExpanded by remember { mutableStateOf(false) }
    var accountPassword by remember { mutableStateOf("") }
    var showPassword by remember { mutableStateOf(false) }

    var autoGeneratedPin by remember { mutableStateOf("Will be auto-generated") }
    var autoGeneratedAccountNumber by remember { mutableStateOf("Will be auto-generated") }

    var accountNameTouched by remember { mutableStateOf(false) }
    var passwordTouched by remember { mutableStateOf(false) }

    var isSubmitting by remember { mutableStateOf(false) }
    var successMessage by remember { mutableStateOf<String?>(null) }
    var errorMessage by remember { mutableStateOf<String?>(null) }

    val trimmedAccountName = accountName.trim()
    val accountNameValid = trimmedAccountName.isNotBlank()
    val passwordValid = accountPassword.length >= 8
    val formValid = accountNameValid && passwordValid

    val accountNameError = if (accountNameTouched && !accountNameValid) "Account name is required" else null
    val passwordError = if (passwordTouched && !passwordValid) "Password must be at least 8 characters" else null

    LaunchedEffect(accountName, accountType, accountPassword) {
        successMessage = null
        errorMessage = null
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                brush = Brush.verticalGradient(
                    listOf(
                        MaterialTheme.colorScheme.background,
                        MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.15f),
                        MaterialTheme.colorScheme.surface
                    )
                )
            )
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(14.dp)
        ) {
            ScreenHeader(
                title = "Request New Account",
                subtitle = "Submit an account request for admin approval",
                onBack = onBack,
                enabled = canGoBack
            )

            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                elevation = CardDefaults.cardElevation(defaultElevation = 4.dp)
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    OutlinedTextField(
                        value = accountName,
                        onValueChange = {
                            accountName = it
                            accountNameTouched = true
                        },
                        modifier = Modifier.fillMaxWidth(),
                        label = { Text("Account Name") },
                        placeholder = { Text("e.g. Peter Main Account") },
                        singleLine = true,
                        isError = accountNameError != null
                    )
                    if (accountNameError != null) {
                        Text(accountNameError, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error)
                    }

                    Text("Type of Account", style = MaterialTheme.typography.labelLarge, fontWeight = FontWeight.SemiBold)
                    Box {
                        OutlinedTextField(
                            value = accountType,
                            onValueChange = {},
                            readOnly = true,
                            label = { Text("Select account type") },
                            trailingIcon = {
                                Icon(
                                    imageVector = Icons.Filled.KeyboardArrowDown,
                                    contentDescription = null,
                                    modifier = Modifier.clickable { accountTypeExpanded = true }
                                )
                            },
                            modifier = Modifier
                                .fillMaxWidth()
                                .clickable { accountTypeExpanded = true }
                        )

                        DropdownMenu(
                            expanded = accountTypeExpanded,
                            onDismissRequest = { accountTypeExpanded = false }
                        ) {
                            REQUESTABLE_ACCOUNT_TYPES.forEach { type ->
                                DropdownMenuItem(
                                    text = { Text(type) },
                                    onClick = {
                                        accountType = type
                                        accountTypeExpanded = false
                                    }
                                )
                            }
                        }
                    }

                    OutlinedTextField(
                        value = accountPassword,
                        onValueChange = {
                            accountPassword = it
                            passwordTouched = true
                        },
                        modifier = Modifier.fillMaxWidth(),
                        label = { Text("Password") },
                        singleLine = true,
                        visualTransformation = if (showPassword) VisualTransformation.None else PasswordVisualTransformation(),
                        trailingIcon = {
                            IconButton(onClick = { showPassword = !showPassword }) {
                                Icon(
                                    imageVector = if (showPassword) Icons.Filled.VisibilityOff else Icons.Filled.Visibility,
                                    contentDescription = null
                                )
                            }
                        },
                        isError = passwordError != null
                    )
                    if (passwordError != null) {
                        Text(passwordError, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error)
                    }

                    OutlinedTextField(
                        value = autoGeneratedPin,
                        onValueChange = {},
                        modifier = Modifier.fillMaxWidth(),
                        label = { Text("PIN Number") },
                        readOnly = true,
                        enabled = false
                    )

                    OutlinedTextField(
                        value = autoGeneratedAccountNumber,
                        onValueChange = {},
                        modifier = Modifier.fillMaxWidth(),
                        label = { Text("Account Number") },
                        readOnly = true,
                        enabled = false
                    )

                    if (!successMessage.isNullOrBlank()) {
                        Text(
                            text = successMessage.orEmpty(),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.primary
                        )
                    }

                    if (!errorMessage.isNullOrBlank()) {
                        Text(
                            text = errorMessage.orEmpty(),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.error
                        )
                    }

                    Button(
                        onClick = {
                            accountNameTouched = true
                            passwordTouched = true

                            if (!formValid || isSubmitting) return@Button

                            isSubmitting = true
                            errorMessage = null

                            scope.launch {
                                val request = CreateAccountRequest(
                                    type = accountType,
                                    openingBalance = 0.0,
                                    customerId = customerId.takeIf { it > 0 },
                                    customerName = trimmedAccountName
                                )

                                when (val result = accountRepository.createAccount(request)) {
                                    is ApiResult.Success -> {
                                        autoGeneratedPin = result.data.accountPin ?: "Generated"
                                        autoGeneratedAccountNumber = result.data.accountNumber
                                        successMessage = "Account request submitted. Status: ${result.data.status}."
                                        onAccountCreated(result.data)
                                    }
                                    is ApiResult.Error -> {
                                        errorMessage = result.message
                                    }
                                }
                                isSubmitting = false
                            }
                        },
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(52.dp),
                        enabled = formValid && !isSubmitting,
                        colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary)
                    ) {
                        if (isSubmitting) {
                            CircularProgressIndicator(
                                modifier = Modifier.size(20.dp),
                                strokeWidth = 2.dp,
                                color = MaterialTheme.colorScheme.onPrimary
                            )
                        } else {
                            Text("Request Account", fontWeight = FontWeight.SemiBold)
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(8.dp))
        }
    }
}
